title: Default Page
options:
  changeTemplate:
    - default
    - simple
    - note
    - notes
    - projects
columns:
  main:
    width: 2/3
    fields:
      main_content:
        type: blocks
        size: huge
  sidebar:
    width: 1/3
    sections:
      meta:
        type: fields
        fields:
          altTitle:
            type: text
            label:
              de: Alternativer Seitentitel
              en: Alternate Page-title
      files:
        type: files
        label: files
